=== UnivParis1/g2t/documents/Circuit_eSignature.dtd
<!ELEMENT CIRCUITS (CIRCUIT+)>
<!ELEMENT CIRCUIT (ETAPE+)>
<!ELEMENT ETAPE (SIGNATAIRES|SIGNATAIRE+)>
<!ELEMENT SIGNATAIRES (SIGNATAIRE+)>
<!ELEMENT SIGNATAIRE (#PCDATA)>
<!ATTLIST CIRCUIT STRUCTURE_RACINE     CDATA #IMPLIED
		  DESCRIPTION          CDATA #REQUIRED>
<!-- Attention : NUMERO doit etre un nombre entier strictement positif -->
<!ATTLIST ETAPE INCLUDE_STRUCT_RACINE  CDATA #IMPLIED
		EXCLUDE_STRUCT_RACINE  CDATA #IMPLIED
		DESCRIPTION            CDATA #REQUIRED
		NUMERO                 CDATA #REQUIRED
		TYPESIGNATURE          (pdfImageStamp|hiddenVisa|visa) #REQUIRED
		TOUTESIGNATURE         (Y|YES|O|OUI|N|NO|NON) #REQUIRED
		PIECEJOINTEOBLIGATOIRE (Y|YES|O|OUI|N|NO|NON) #REQUIRED
		OBLIGATOIRE            (Y|YES|O|OUI|N|NO|NON) #REQUIRED>
<!ATTLIST SIGNATAIRE TYPESIGNATAIRE    (DEMANDEUR|RESPONSABLE|RESPONSABLE_N2|DIRECTEUR_RACINE|AGENT|RESPONSABLE_STRUCT) #REQUIRED>

=== UnivParis1/g2t/documents/Circuit_CET_exemple.xml
<?xml version="1.0"?>
<!DOCTYPE CIRCUITS SYSTEM "Circuit_eSignature.dtd">
<CIRCUITS>
	<CIRCUIT STRUCTURE_RACINE="" DESCRIPTION="Alimentation/Option CET">
		<ETAPE NUMERO="1" DESCRIPTION="Signature de l'agent" TYPESIGNATURE="pdfImageStamp" TOUTESIGNATURE="NON" PIECEJOINTEOBLIGATOIRE="NON" OBLIGATOIRE="OUI">
			<SIGNATAIRE TYPESIGNATAIRE="DEMANDEUR"/>
		</ETAPE>
		<ETAPE NUMERO="2" DESCRIPTION="Visa du responsable" TYPESIGNATURE="visa" TOUTESIGNATURE="NON" PIECEJOINTEOBLIGATOIRE="NON" OBLIGATOIRE="OUI">
			<SIGNATAIRE TYPESIGNATAIRE="RESPONSABLE"/>
		</ETAPE>
		<ETAPE NUMERO="3" DESCRIPTION="Visa du QVT" TYPESIGNATURE="hiddenVisa" TOUTESIGNATURE="NON" PIECEJOINTEOBLIGATOIRE="NON" OBLIGATOIRE="OUI">
			<SIGNATAIRE TYPESIGNATAIRE="AGENT">90786</SIGNATAIRE>
			<SIGNATAIRE TYPESIGNATAIRE="AGENT">94693</SIGNATAIRE>
			<SIGNATAIRE TYPESIGNATAIRE="AGENT">97316</SIGNATAIRE>
		</ETAPE>
		<ETAPE NUMERO="4" DESCRIPTION="Visa du responsable du QVT" TYPESIGNATURE="hiddenVisa" TOUTESIGNATURE="NON" PIECEJOINTEOBLIGATOIRE="NON" OBLIGATOIRE="OUI">
			<SIGNATAIRE TYPESIGNATAIRE="RESPONSABLE_STRUCT">DGEE_4</SIGNATAIRE>
		</ETAPE>
		<ETAPE NUMERO="5" DESCRIPTION="Signature de l'autorite" TYPESIGNATURE="pdfImageStamp" TOUTESIGNATURE="NON" PIECEJOINTEOBLIGATOIRE="NON" OBLIGATOIRE="OUI">
			<SIGNATAIRE TYPESIGNATAIRE="RESPONSABLE_STRUCT">DGE_3</SIGNATAIRE>
			<SIGNATAIRE TYPESIGNATAIRE="RESPONSABLE_STRUCT">DG_2</SIGNATAIRE>
		</ETAPE>
	</CIRCUIT>
</CIRCUITS>

=== UnivParis1/g2t/documents/Circuit_Teletravail_exemple.xml
<?xml version="1.0"?>
<!DOCTYPE CIRCUITS SYSTEM "Circuit_eSignature.dtd">
<CIRCUITS>
	<CIRCUIT STRUCTURE_RACINE="" DESCRIPTION="Circuit t&#xE9;l&#xE9;travail par d&#xE9;faut">
		<ETAPE NUMERO="1" DESCRIPTION="Signature de l'agent" TYPESIGNATURE="pdfImageStamp" TOUTESIGNATURE="NON" PIECEJOINTEOBLIGATOIRE="OUI" OBLIGATOIRE="OUI">
			<SIGNATAIRE TYPESIGNATAIRE="DEMANDEUR"/>
		</ETAPE>
		<ETAPE NUMERO="2" DESCRIPTION="Visa du responsable" TYPESIGNATURE="visa" TOUTESIGNATURE="NON" PIECEJOINTEOBLIGATOIRE="NON" OBLIGATOIRE="OUI">
			<SIGNATAIRE TYPESIGNATAIRE="RESPONSABLE"/>
		</ETAPE>
		<ETAPE NUMERO="3" DESCRIPTION="Visa du responsable N+2" TYPESIGNATURE="hiddenVisa" TOUTESIGNATURE="NON" PIECEJOINTEOBLIGATOIRE="NON" OBLIGATOIRE="NON">
			<SIGNATAIRE TYPESIGNATAIRE="RESPONSABLE_N2"/>
		</ETAPE>
		<ETAPE NUMERO="4" DESCRIPTION="Visa du QVT" TYPESIGNATURE="hiddenVisa" TOUTESIGNATURE="NON" PIECEJOINTEOBLIGATOIRE="NON" OBLIGATOIRE="OUI">
			<SIGNATAIRE TYPESIGNATAIRE="AGENT">90786</SIGNATAIRE>
			<SIGNATAIRE TYPESIGNATAIRE="AGENT">94693</SIGNATAIRE>
			<SIGNATAIRE TYPESIGNATAIRE="AGENT">97316</SIGNATAIRE>
		</ETAPE>
		<ETAPE NUMERO="5" DESCRIPTION="Signature du responsable du QVT" TYPESIGNATURE="hiddenVisa" TOUTESIGNATURE="NON" PIECEJOINTEOBLIGATOIRE="NON" OBLIGATOIRE="OUI">
			<SIGNATAIRE TYPESIGNATAIRE="RESPONSABLE_STRUCT">DGEE_4</SIGNATAIRE>
		</ETAPE>
		<ETAPE NUMERO="6" DESCRIPTION="Signature de l'autorite" TYPESIGNATURE="pdfImageStamp" TOUTESIGNATURE="NON" PIECEJOINTEOBLIGATOIRE="NON" OBLIGATOIRE="OUI">
			<SIGNATAIRE TYPESIGNATAIRE="RESPONSABLE_STRUCT">DGE_3</SIGNATAIRE>
			<SIGNATAIRE TYPESIGNATAIRE="RESPONSABLE_STRUCT">DG_2</SIGNATAIRE>
		</ETAPE>
	</CIRCUIT>
	<CIRCUIT STRUCTURE_RACINE="IU2_3 IU1_3 SC4_3" DESCRIPTION="Circuit t&#xE9;l&#xE9;travail pour les biblioth&#xE8;ques">
		<ETAPE NUMERO="1" DESCRIPTION="Signature de l'agent" TYPESIGNATURE="pdfImageStamp" TOUTESIGNATURE="NON" PIECEJOINTEOBLIGATOIRE="OUI" OBLIGATOIRE="OUI">
			<SIGNATAIRE TYPESIGNATAIRE="DEMANDEUR"/>
		</ETAPE>
		<ETAPE NUMERO="2" DESCRIPTION="Visa du responsable" TYPESIGNATURE="visa" TOUTESIGNATURE="NON" PIECEJOINTEOBLIGATOIRE="NON" OBLIGATOIRE="OUI">
			<SIGNATAIRE TYPESIGNATAIRE="RESPONSABLE"/>
		</ETAPE>
		<ETAPE NUMERO="3" INCLUDE_STRUCT_RACINE="IU2_3" DESCRIPTION="Visa du responsable du service administratif et du directeur - BIS" TYPESIGNATURE="hiddenVisa" TOUTESIGNATURE="OUI" PIECEJOINTEOBLIGATOIRE="NON" OBLIGATOIRE="OUI">
			<SIGNATAIRE TYPESIGNATAIRE="DIRECTEUR_RACINE"/>
			<SIGNATAIRE TYPESIGNATAIRE="RESPONSABLE_STRUCT">IU2A_4</SIGNATAIRE>
		</ETAPE>
		<ETAPE NUMERO="3" INCLUDE_STRUCT_RACINE="IU1_3" DESCRIPTION="Visa du responsable du service administratif et du directeur - Cujas" TYPESIGNATURE="hiddenVisa" TOUTESIGNATURE="OUI" PIECEJOINTEOBLIGATOIRE="NON" OBLIGATOIRE="OUI">
			<SIGNATAIRE TYPESIGNATAIRE="DIRECTEUR_RACINE"/>
			<SIGNATAIRE TYPESIGNATAIRE="RESPONSABLE_STRUCT">IU1H_4</SIGNATAIRE>
		</ETAPE>
		<ETAPE NUMERO="3" INCLUDE_STRUCT_RACINE="SC4_3" DESCRIPTION="Visa du responsable du service administratif et du directeur - SCD" TYPESIGNATURE="hiddenVisa" TOUTESIGNATURE="OUI" PIECEJOINTEOBLIGATOIRE="NON" OBLIGATOIRE="OUI">
			<SIGNATAIRE TYPESIGNATAIRE="DIRECTEUR_RACINE"/>
			<SIGNATAIRE TYPESIGNATAIRE="RESPONSABLE_STRUCT">SC4B_4</SIGNATAIRE>
		</ETAPE>
		<ETAPE NUMERO="4" DESCRIPTION="Visa du QVT" TYPESIGNATURE="hiddenVisa" TOUTESIGNATURE="NON" PIECEJOINTEOBLIGATOIRE="NON" OBLIGATOIRE="OUI">
			<SIGNATAIRE TYPESIGNATAIRE="AGENT">90786</SIGNATAIRE>
			<SIGNATAIRE TYPESIGNATAIRE="AGENT">94693</SIGNATAIRE>
			<SIGNATAIRE TYPESIGNATAIRE="AGENT">97316</SIGNATAIRE>
		</ETAPE>
		<ETAPE NUMERO="5" DESCRIPTION="Signature du responsable du QVT" TYPESIGNATURE="hiddenVisa" TOUTESIGNATURE="NON" PIECEJOINTEOBLIGATOIRE="NON" OBLIGATOIRE="OUI">
			<SIGNATAIRE TYPESIGNATAIRE="RESPONSABLE_STRUCT">DGEE_4</SIGNATAIRE>
		</ETAPE>
		<ETAPE NUMERO="6" DESCRIPTION="Signature de l'autorite" TYPESIGNATURE="pdfImageStamp" TOUTESIGNATURE="NON" PIECEJOINTEOBLIGATOIRE="NON" OBLIGATOIRE="OUI">
			<SIGNATAIRE TYPESIGNATAIRE="RESPONSABLE_STRUCT">DGE_3</SIGNATAIRE>
			<SIGNATAIRE TYPESIGNATAIRE="RESPONSABLE_STRUCT">DG_2</SIGNATAIRE>
		</ETAPE>
	</CIRCUIT>
</CIRCUITS>
